2022-08-30 02:56:15,169 INFO     Logfile will be written to ../logs\neet_premerge_2022_08_30_02_56_15.txt
2022-08-30 02:56:15,169 INFO     Reading '../data\interim\neet_annotated.csv'
2022-08-30 02:56:15,169 INFO     Reading all data as str
2022-08-30 02:56:15,169 ERROR    Uncaught Exception
Traceback (most recent call last):
  File "C:\Users\abhmu\s22_buckinghamshire\scripts\data\neet_premerge.py", line 75, in <module>
    df = d.load_csv(  # We are now going to filter out the necessary columns
  File "c:\users\abhmu\s22_buckinghamshire\src\data_utils.py", line 208, in load_csv
    df = pd.read_csv(fp, keep_default_na=False, dtype=pd.StringDtype())
  File "C:\Users\abhmu\s22_buckinghamshire\venv\lib\site-packages\pandas\util\_decorators.py", line 311, in wrapper
    return func(*args, **kwargs)
  File "C:\Users\abhmu\s22_buckinghamshire\venv\lib\site-packages\pandas\io\parsers\readers.py", line 680, in read_csv
    return _read(filepath_or_buffer, kwds)
  File "C:\Users\abhmu\s22_buckinghamshire\venv\lib\site-packages\pandas\io\parsers\readers.py", line 575, in _read
    parser = TextFileReader(filepath_or_buffer, **kwds)
  File "C:\Users\abhmu\s22_buckinghamshire\venv\lib\site-packages\pandas\io\parsers\readers.py", line 934, in __init__
    self._engine = self._make_engine(f, self.engine)
  File "C:\Users\abhmu\s22_buckinghamshire\venv\lib\site-packages\pandas\io\parsers\readers.py", line 1218, in _make_engine
    self.handles = get_handle(  # type: ignore[call-overload]
  File "C:\Users\abhmu\s22_buckinghamshire\venv\lib\site-packages\pandas\io\common.py", line 786, in get_handle
    handle = open(
FileNotFoundError: [Errno 2] No such file or directory: "'../data\\interim\\neet_annotated.csv'"
